"""empty message

Revision ID: 6fc024cd1fa3
Revises: 122b0bf6e2b8
Create Date: 2021-10-25 10:18:09.071610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc024cd1fa3'
down_revision = '122b0bf6e2b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
